// Static member classes instead of multiple top-level classes
public class Test {
    public static void main(String[] args) {
        System.out.println(Utensil.NAME + Dessert.NAME);
    }
    private static class Utensil {
        static final String NAME = "pan";
    }
    private static class Dessert {
        static final String NAME = "cake";
    }
}

// The lesson is clear: Never put multiple top-level classes or interfaces in a
//single source file. Following this rule guarantees that you can’t have multiple
//definitions for a single class at compile time. This in turn guarantees that the
//class files generated by compilation, and the behavior of the resulting program,
//are independent of the order in which the source files are passed to the compiler.